In [1]:
cd C:\Users\HP\OneDrive\Documents

C:\Users\HP\OneDrive\Documents

In [2]:
pwd

'C:\\Users\\HP\\OneDrive\\Documents'

In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv('hiring.csv')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  6 non-null      object
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

In [7]:
df.head()

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [8]:
df.tail()

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
df["test_score(out of 10)"].median()

8.0

In [10]:
mean_test_score = df["test_score(out of 10)"].mean()
df["test_score(out of 10)"].fillna(mean_test_score, inplace = True)
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN               8.000000                           9      50000
1        NaN               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [1]:
mean_experience = df["experience)"].mean()
df["experience"].fillna(mean_experience, inplace = True)
df

NameError: name 'df' is not defined

In [ ]:
mean_test_score = df["test_score(out of 10)"].mean()
df["test_score(out of 10)"].fillna(mean_test_score, inplace = True)
df

In [11]:
x=df[['test_score(out of 10)','interview_score(out of 10)']]
y=df['salary($)']

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [13]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(6, 2)
(6,)
(2, 2)
(2,)

In [14]:
from sklearn.linear_model import LinearRegression
multi_lin= LinearRegression()
multi_lin.fit(x_train,y_train)

LinearRegression()

In [15]:
predicted_values = multi_lin.predict(x_test)
predicted_values

array([71135.10692582, 66910.86422044])

In [16]:
multi_lin.coef_

array([  799.46189173, -1408.0809018 ])

In [17]:
multi_lin.intercept_

73187.89720276477

In [18]:
multi_lin.score(x_train,y_train)

0.10936226269353577

In [19]:
multi_lin.score(x_test,y_test)

-76.52169141651217

In [20]:
y_test

1    45000
0    50000
Name: salary($), dtype: int64

In [21]:
pd.DataFrame({"Actual_Data" : y_test,
             "New_Prediction" : predicted_values,
             "Error":y_test - predicted_values
             })

   Actual_Data  New_Prediction         Error
1        45000    71135.106926 -26135.106926
0        50000    66910.864220 -16910.864220

In [22]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
MSE = mean_squared_error(y_test,predicted_values)
MAE = mean_absolute_error(y_test,predicted_values)
RMSE = np.sqrt(MSE)
r_squared = r2_score(y_test,predicted_values)

In [23]:
MSE

484510571.35320103

In [24]:
MAE

21522.985573131707

In [25]:
RMSE

22011.600835768422